language: ruby
rvm:
- 2.2.0
- 2.1.5
env:
  global:
  - secure: mVOTPzF5AOokBVUmC8rqGb1ZSQc8RnWfarni5fEBzmdoQ1zz++X3V3WSWfB1YebK5UEGOppngu7dgAn5okkcQI+ohBk9yvWv2WMSWGwE3/ZHq2tKxo2TAvHbfS1vPCLFilzaF3D3csf9l89Z0Kyv+wY78un+ZFcS2UwCjL/7uwk=
  - secure: bXVE1tnIITCwFWvfM/4DiiCzO94dSQTN0IkD+Nul4abqH3FMvWIwiNwBUdePK3NL4LbeIp0LfNeNthQm3kaHAd3WhpYuBWtvwhpF3vcghRoJw9+MzNMDQySC4nYoje0T1wstAl9AYRNz9C1qFBp9Ba9sb2hCnVBFot+fDzLJssc=
