language: ruby
rvm:
- 2.2.0
env:
  global:
  - secure: Pp7JaGVsZyPJPaZHgpWEibRDtpg4aWWTC9yb7SITdXTJ7AN5gZPLIyNuYfY937Ypq2JoJAI2yhJzfMPTQJ/FwF8OV1d9dUZyDv3R6aMsE41xJoL6X2bLtyh3TduULSIeiemoOEk4Y5JqOJb8JEyFMd0n+0AD+hn+HBPysIfwgHM=
  - secure: JWJ1rHozorq1b2eC5tr0f8qejFvBbmWElTiGFFjxiOMXBwTBGbqTwSUhwyj0oNCfNcSvHRLXbUtDHLch+v7G/xHKzC91xBqpzCVoQSpKdC2f8/coJTDqQ2NOeatTY470lkOky5gGm/+i+ezL+fhqMPMMijZDtsNw4SOIiIRqdow=
